NAME=goal
VIEWPDF=evince
BIBTEXSRCS=goal.bib
USE_PDFLATEX=1
CLEAN_FILES+=goal.synctex.gz goal.bib goal.tar.gz *.bak *.tmp *.fls *.tatexmk *.fdb_latexmk
EXTRA_DIST+=*.pdf iop* 

include /usr/share/latex-mk/latex.gmk
