NAME=main
VIEWPDF=evince
BIBTEXSRCS=main.bib
USE_PDFLATEX=1
CLEAN_FILES+=main.synctex.gz main.bib main.tar.gz *.bak *.tmp *.fls *.tatexmk *.fdb_latexmk
EXTRA_DIST+=*.pdf iop* 

include /usr/share/latex-mk/latex.gmk
